# Site settings
title: Jin-Ho King, Attorney at Law
email: j@kingesq.us
description: > # this means to ignore newlines until "baseurl:"
  Jin-Ho King, Attorney at Law, focuses his practice on appeals
  and complex litigation matters.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kingesq.us" # the base hostname & protocol for your site
twitter_username: jinho_king
github_username:  kjinho

default:
  title: "Jin-Ho King, Attorney at Law"

# Build settings
markdown: kramdown
